# sample OpenAPI definition with microgateway extensions 

openapi: 3.0.0
info:
  version: 1.0.0
  title: MyRetailStore
x-wso2-basePath: /retailStore
x-wso2-production-endpoints:
  urls:
  - http://localhost:50000
paths:
  /order:
    post:
      # REST to gRPC interceptor is applied here
      x-wso2-request-interceptor: java:org.mgw_demo.order_service_interceptor.OrderInterceptor
      summary: place an order
      operationId: orderRequest
      responses:
        '200':
          description: Expected response to a valid request
  /checkItem:
    get:
      summary: check availability of an item
      operationId: checkItemRequest
      responses:
        '200':
          description: Expected response to a valid request
